### ISSUE TITLE
Check out pragmatics

### ISSUE THREAD

**Issue by phibenz** [carlini/yet-another-applied-llm-benchmark#13]
Hi there, 

your repo inspired me, so I recently developed a project called [pragmatics](https://github.com/phibenz/pragmatics), which is a template engine achieving the same purpose as "yet-another-applied-llm-benchmark". I already started to port some of your test cases into [pragmatics-templates](https://github.com/phibenz/pragmatics-templates), and am planning to add many more soon. 

I just wanted to say thank you for this project and keep up the fantastic work.

**Comment by carlini** [comment]
Glad you liked it!
