### ISSUE TITLE
[URGENT] regarding creation of new class in evaluator.py

### ISSUE THREAD

**Issue by sudhanshu-myl** [carlini/yet-another-applied-llm-benchmark#23]
Hi,
I am using this framework to evaluate few non-coding related scenarios.
Based on my usecase, I am asking eval_llm to score each of the condition provided in the evaluation prompt.

I have written a custom class QueryEvaluator which extends Node class. Code given below. I am able to print the scores and the final_score claculation, but it is giving the following error while running the testcase. Please let me know how to solve this issue. Maybe the problem is with the return type of __call__ method of QueryEvaluator class.

Here is the Query Evaluator class:
```
class QueryEvaluator(Node):
    def __init__(self, weights = None):
        # Initialize the evaluator with default weights if none are provided
        if weights == None:
            self.weights = [0.35,0.3,0.10,0.10]
        else:
            self.weights = weights

    def __call__(self, output):
        """
        Evaluates the SQL query based on the provided scores and weights.
        
        :param scores: List of scores for each condition [Syntax_Score, Table_Score, Logic_Score, Function_Score]
        :return: Final score and query validity ("Valid query" or "Invalid query")
        """
        self.output = output
        match = re.search(r'\[.*?\]', self.output)
        if match:
            # Extract the array part of the string
            array_str = match.group(0)
            
            # Convert the string to a Python list
            scores = ast.literal_eval(array_str)
        else:
            scores=[]

        print("scores",scores)
        # Calculate the final score using the weights
        final_score = sum(w * s for w, s in zip(self.weights, scores))
        print("final score = ", final_score)

        reason = Reason(node=self, children=[scores, self.weights])
        
        return [(final_score,reason)]
```

Here is the test code (I am pasting only calling function):
```
TestMissingStep = prompt >> LLMRun() >> LLMRun(evaluation, llm=EVAL_LLM) >> ExtractCode() >> QueryEvaluator()
    

if __name__ == "__main__":
    print(run_test(TestMissingStep))
```

Here is the error while executing the test file:

UNKNOWN NODE TYPE: <evaluator.QueryEvaluator object at 0x7fef525784f0>

Note: Till ExtractCode() output is coming fine.

Please help me in this.
TIA!

**Comment by carlini** [comment]
You'll need to add your new node type to the formatter, so that this assert doesn't trigger

https://github.com/carlini/yet-another-applied-llm-benchmark/blob/a35d306f34d9f5785e60587f175edeaad5c38862/create_results_html.py#L104

**Comment by sudhanshu-myl** [comment]
Thank you for your answer.
I have added the node type but it is still giving me the same error. Also, is the return type of QueryEvaluator fine? I had trouble understanding the return type of methods defined in evaluator.py Is there some documentation regarding the same.
Here's what i added to create_results_html.py:
```
elif reason.node == QueryEvaluator:
        return f"{pounds} Query Evaluator\nTesting if the SQL query is correct format or not `{reason.children[0]}` : {reason.children[1]}\n"
```

**Comment by carlini** [comment]
I see, notice how all of the other lines pass `node=type(self)` and not `node=self`. You need to do this too.

See, e.g., here this one (or any other)
https://github.com/carlini/yet-another-applied-llm-benchmark/blob/a35d306f34d9f5785e60587f175edeaad5c38862/evaluator.py#L225

**Comment by sudhanshu-myl** [comment]
Thank you !
Its working now.
