### ISSUE TITLE
WhatIsStarStar is too strict

### ISSUE THREAD

**Issue by dbieber** [carlini/yet-another-applied-llm-benchmark#6]
I'm fairly sure the majority of the model outputs are correct but are marked wrong:

Here is the text of the test as a reminder:
```
from evaluator import *

DESCRIPTION = "Test if the model can understand and interpret a request to gitignore any file called \".KEYFILE\" regardless of its location in a repository."

TAGS = ['explain']

question = """
gitignore any file called .KEYFILE anywhere
"""

TestWhatIsStarStar = question >> LLMRun() >> SubstringEvaluator("**/.KEYFILE")

if __name__ == "__main__":
    print(run_test(TestWhatIsStarStar))
```

I think that just adding `.KEYFILE` to a gitignore is sufficient, and `**/.KEYFILE` is not needed.

https://git-scm.com/docs/gitignore confirms this:

```A leading "**" followed by a slash means match in all directories. For example, "**/foo" matches file or directory "foo" anywhere, the same as pattern "foo". "**/foo/bar" matches file or directory "bar" anywhere that is directly under directory "foo".```

To adjust the test, you could require that .KEYFILE be anywhere in the key/ directory (including in any subdir). Then **/.KEYFILE would be a necessary substring of the result.

**Comment by carlini** [comment]
Oops, yes you're right. I'll fix the question to say ignore any .KEYFILE under a directory called foo and then test for **/foo/.KEYFILE[
